### ISSUE TITLE
paramiko.ssh_exception.SSHException: Negotiation failed, after 2.5.0 released.

### ISSUE THREAD

**Issue by dovahcrow** [paramiko/paramiko#1455]
Through `git bisect` I find this commit d888078 is causing the issue.

**Comment by dovahcrow** [comment]
The client and the server may negotiate to use group16 sha512 kex but it seems like is not correctly implemented.

**Comment by ploxiln** [comment]
Can you post debug logs from paramiko? Perhaps like so:

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

I ask because this kex algorithm seems to work for me:

```
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.5.0
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u6
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_7.4p1)
DEBUG:paramiko.transport:kex algos:['curve25519-sha256', 'curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group16-sha512', 'diffie-hellman-group18-sha512', 'diffie-hellman-group14-sha256', 'diffie-hellman-group14-sha1'] server key:['ssh-rsa', 'rsa-sha2-512', 'rsa-sha2-256', 'ecdsa-sha2-nistp256', 'ssh-ed25519'] client encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] server encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group16-sha512
DEBUG:paramiko.transport:HostKey agreed: ecdsa-sha2-nistp256
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexGroup16SHA512 specified hash_algo <built-in function openssl_sha512>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Trying SSH agent key b'db274a290eb2606dc90dae81c7c76d00'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (publickey) successful!
```

**Comment by ploxiln** [comment]
(I suppose that success was paramiko just on the client side, maybe the failure was with paramiko on the server side?)

**Comment by dovahcrow** [comment]
I'm using it from client side
```
DEB [20190611-21:45:22.962] thr=1   paramiko.transport: starting thread (client mode): 0xfddb550
DEB [20190611-21:45:22.963] thr=1   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.4.1
DEB [20190611-21:45:22.993] thr=1   paramiko.transport: Remote version/idstring: SSH-2.0-srtSSHServer_11.00
INF [20190611-21:45:22.994] thr=1   paramiko.transport: Connected (version 2.0, client srtSSHServer_11.00)
DEB [20190611-21:45:23.000] thr=1   paramiko.transport: kex algos:['diffie-hellman-group14-sha256', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group14-sha1', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group1-sha1', 'diffie-hellman-group-exchange-sha512@ssh.com', 'diffie-hellman-group16-sha256', 'diffie-hellman-group16-sha512', 'diffie-hellman-group18-sha512'] server key:['ssh-rsa'] client encrypt:['aes256-cbc', 'twofish256-cbc', 'aes128-cbc', 'blowfish-cbc', '3des-ctr', '3des-cbc'] server encrypt:['aes256-cbc', 'twofish256-cbc', 'aes128-cbc', 'blowfish-cbc', '3des-ctr', '3des-cbc'] client mac:['hmac-sha1', 'hmac-sha2-224', 'hmac-sha2-256', 'hmac-sha2-384', 'hmac-sha2-512'] server mac:['hmac-sha1', 'hmac-sha2-224', 'hmac-sha2-256', 'hmac-sha2-384', 'hmac-sha2-512'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
DEB [20190611-21:45:23.001] thr=1   paramiko.transport: Kex agreed: diffie-hellman-group16-sha512
DEB [20190611-21:45:23.001] thr=1   paramiko.transport: HostKey agreed: ssh-rsa
DEB [20190611-21:45:23.001] thr=1   paramiko.transport: Cipher agreed: aes128-cbc
DEB [20190611-21:45:23.001] thr=1   paramiko.transport: MAC agreed: hmac-sha2-256
DEB [20190611-21:45:23.001] thr=1   paramiko.transport: Compression agreed: none
INF [20190611-21:45:23.263] thr=1   paramiko.transport: Disconnect (code 3): invalid DH value
```

**Comment by dovahcrow** [comment]
I guess maybe this is a corner case for the windows ssh server (srtSShServer)

**Comment by drwahl** [comment]
I think we're seeing this with ansible as well for some Juniper devices. I'll try to get a worthwhile debug/trace to add, but paramiko was working to our JunOS devices with 2.4.2, and it's failing with 2.5.0.

**Comment by ploxiln** [comment]
With paramiko-2.4.2 it would have negotiated a different kex because diffie-hellman-group16-sha512 was not offered.

For debug and/or workaround you can try changing paramiko's preferred-kex list. If your code uses the Transport directly, you can call Transport.get_security_options(), and then get and set the "kex" property of the returned object to a custom list or tuple. If you use the SSHClient or another library that uses paramiko underneath, you can monkey-patch the preffered-kex list first, like so (admittedly hacky):

```python
from paramiko import transport
transport.Transport._preferred_kex = (
        'ecdh-sha2-nistp256',
        'ecdh-sha2-nistp384',
        'ecdh-sha2-nistp521',
        # 'diffie-hellman-group16-sha512',  # disable
        'diffie-hellman-group-exchange-sha256',
        'diffie-hellman-group14-sha256',
        'diffie-hellman-group-exchange-sha1',
        'diffie-hellman-group14-sha1',
        'diffie-hellman-group1-sha1',
)
```

**Comment by miverson** [comment]
I'm confirming the same behavior. 

Paramiko 2.5.0, server mode. Client is seeing a similar error message: "signature check failed"

Local version/idstring: SSH-2.0-paramiko_2.5.0
Remote version/idstring: SSH-2.0-1.82 sshlib: ClientSftp
Connected (version 2.0, client 1.82)
kex algos:['diffie-hellman-group16-sha512', 'diffie-hellman-group14-sha256', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1'] server key:['ssh-rsa', 'ssh-dss'] client encrypt:['twofish256-cbc', 'aes256-cbc', 'aes256-ctr', 'twofish-cbc', '3des-cbc', 'twofish128-cbc', 'aes128-cbc', 'aes128-ctr', 'cast128-cbc', 'blowfish-cbc', 'arcfour'] server encrypt:['twofish256-cbc', 'aes256-cbc', 'aes256-ctr', 'twofish-cbc', '3des-cbc', 'twofish128-cbc', 'aes128-cbc', 'aes128-ctr', 'cast128-cbc', 'blowfish-cbc', 'arcfour'] client mac:['hmac-sha2-256', 'hmac-sha1', 'hmac-md5', 'hmac-sha1-96', 'hmac-md5-96'] server mac:['hmac-sha2-256', 'hmac-sha1', 'hmac-md5', 'hmac-sha1-96', 'hmac-md5-96'] client compress:['zlib', 'none'] server compress:['zlib', 'none'] client lang:[''] server lang:[''] kex follows?False
Kex agreed: diffie-hellman-group16-sha512
HostKey agreed: ssh-rsa
Cipher agreed: aes256-cbc
MAC agreed: hmac-sha2-256
Compression agreed: none
kex engine KexGroup16SHA512 specified hash_algo <built-in function openssl_sha512>

**Comment by miverson** [comment]
I can confirm that I am experiencing this problem for both "diffie-hellman-group16-sha512" and "diffie-hellman-group14-sha256" KEX algorithms in server mode. The client is 'SSH-2.0-1.82 sshlib: ClientSftp'

I haven't been able to confirm whether this happens with other clients.

**Comment by miverson** [comment]
I'm able to trigger the same error using openssh. Debug output below:

```
$ ssh -vvv -o KexAlgorithms=diffie-hellman-group14-sha256 xxxx@127.0.0.1
OpenSSH_7.9p1, LibreSSL 2.7.3
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 48: Applying options for *
debug2: resolve_canonicalize: hostname 127.0.0.1 is address
debug2: ssh_connect_direct
debug1: Connecting to 127.0.0.1 [127.0.0.1] port 22.
debug1: Connection established.
debug1: identity file ~/.ssh/id_rsa type 0
debug1: identity file ~/.ssh/id_rsa-cert type -1
debug1: identity file ~/.ssh/id_dsa type -1
debug1: identity file ~/.ssh/id_dsa-cert type -1
debug1: identity file ~/.ssh/id_ecdsa type -1
debug1: identity file ~/.ssh/id_ecdsa-cert type -1
debug1: identity file ~/.ssh/id_ed25519 type 3
debug1: identity file ~/.ssh/id_ed25519-cert type -1
debug1: identity file ~/.ssh/id_xmss type -1
debug1: identity file ~/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.9
debug1: Remote protocol version 2.0, remote software version paramiko_2.5.0
debug1: no match: paramiko_2.5.0
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 127.0.0.1:22 as 'xxxx'
debug3: hostkeys_foreach: reading file "~/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file ~/.ssh/known_hosts:119
debug3: load_hostkeys: loaded 1 keys from 127.0.0.1
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: diffie-hellman-group14-sha256,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group16-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: host key algorithms: ssh-ed25519,ecdsa-sha2-nistp256,ssh-rsa,ssh-dss
debug2: ciphers ctos: aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc
debug2: ciphers stoc: aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc
debug2: MACs ctos: hmac-sha2-256,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1
debug2: MACs stoc: hmac-sha2-256,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1
debug2: compression ctos: zlib@openssh.com,none
debug2: compression stoc: zlib@openssh.com,none
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: diffie-hellman-group14-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
debug1: sending SSH2_MSG_KEXDH_INIT
debug2: bits set: 1049/2048
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEXDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:SDSDFSDFSDFSDFSDFSDF/ZCwo
debug3: hostkeys_foreach: reading file "~/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file ~/.ssh/known_hosts:119
debug3: load_hostkeys: loaded 1 keys from 127.0.0.1
debug1: Host '127.0.0.1' is known and matches the ECDSA host key.
debug1: Found key in ~/.ssh/known_hosts:119
debug2: bits set: 1039/2048
ssh_dispatch_run_fatal: Connection to 127.0.0.1 port 22: incorrect signature


$ ssh -vvv -o KexAlgorithms=diffie-hellman-group16-sha512 xxxx@127.0.0.1
OpenSSH_7.9p1, LibreSSL 2.7.3
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 48: Applying options for *
debug2: resolve_canonicalize: hostname 127.0.0.1 is address
debug2: ssh_connect_direct
debug1: Connecting to 127.0.0.1 [127.0.0.1] port 22.
debug1: Connection established.
debug1: identity file ~/.ssh/id_rsa type 0
debug1: identity file ~/.ssh/id_rsa-cert type -1
debug1: identity file ~/.ssh/id_dsa type -1
debug1: identity file ~/.ssh/id_dsa-cert type -1
debug1: identity file ~/.ssh/id_ecdsa type -1
debug1: identity file ~/.ssh/id_ecdsa-cert type -1
debug1: identity file ~/.ssh/id_ed25519 type 3
debug1: identity file ~/.ssh/id_ed25519-cert type -1
debug1: identity file ~/.ssh/id_xmss type -1
debug1: identity file ~/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.9
debug1: Remote protocol version 2.0, remote software version paramiko_2.5.0
debug1: no match: paramiko_2.5.0
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 127.0.0.1:22 as 'xxxx'
debug3: hostkeys_foreach: reading file "~/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file ~/.ssh/known_hosts:119
debug3: load_hostkeys: loaded 1 keys from 127.0.0.1
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: diffie-hellman-group16-sha512,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group16-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: host key algorithms: ssh-ed25519,ecdsa-sha2-nistp256,ssh-rsa,ssh-dss
debug2: ciphers ctos: aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc
debug2: ciphers stoc: aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc
debug2: MACs ctos: hmac-sha2-256,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1
debug2: MACs stoc: hmac-sha2-256,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1
debug2: compression ctos: zlib@openssh.com,none
debug2: compression stoc: zlib@openssh.com,none
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: diffie-hellman-group16-sha512
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
debug1: sending SSH2_MSG_KEXDH_INIT
debug2: bits set: 2012/4096
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEXDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:SDSDFSDFSDFSDFSDFSDF/ZCwo
debug3: hostkeys_foreach: reading file "~/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file ~/.ssh/known_hosts:119
debug3: load_hostkeys: loaded 1 keys from 127.0.0.1
debug1: Host '127.0.0.1' is known and matches the ECDSA host key.
debug1: Found key in ~/.ssh/known_hosts:119
debug2: bits set: 1973/4096
ssh_dispatch_run_fatal: Connection to 127.0.0.1 port 22: incorrect signature
```

**Comment by miverson** [comment]
Here is the server side errors:
```
sshd.py:transport.py:1760 DEBUG    Kex agreed: diffie-hellman-group14-sha256
sshd.py:transport.py:1760 DEBUG    HostKey agreed: ecdsa-sha2-nistp256
sshd.py:transport.py:1760 DEBUG    Cipher agreed: aes128-ctr
sshd.py:transport.py:1760 DEBUG    MAC agreed: hmac-sha2-256-etm@openssh.com
sshd.py:transport.py:1760 DEBUG    Compression agreed: none
sshd.py:transport.py:1760 DEBUG    kex engine KexGroup14SHA256 specified hash_algo <built-in function openssl_sha256>
sshd.py:transport.py:1760 DEBUG    EOF in transport thread
```

```
sshd.py:transport.py:1760 DEBUG    Kex agreed: diffie-hellman-group16-sha512
sshd.py:transport.py:1760 DEBUG    HostKey agreed: ecdsa-sha2-nistp256
sshd.py:transport.py:1760 DEBUG    Cipher agreed: aes128-ctr
sshd.py:transport.py:1760 DEBUG    MAC agreed: hmac-sha2-256-etm@openssh.com
sshd.py:transport.py:1760 DEBUG    Compression agreed: none
sshd.py:transport.py:1760 DEBUG    kex engine KexGroup16SHA512 specified hash_algo <built-in function openssl_sha512>
sshd.py:transport.py:1760 DEBUG    EOF in transport thread
```

**Comment by bitprophet** [comment]
There's a lot to unpack here - I think we're seeing 2-2 1/2 different issues:

- @dovahcrow and @drwahl appear to be finding that non-OpenSSH servers are triggering a problem with Paramiko's client side.
  - This may end up classified with the vexing but hard to handle pile (due to me not running Windows or having any custom networking hardware to test against) of extant problems where we run into non-OpenSSH-compatible server problems.
  - As always if somebody can identify a patch that fixes these issues w/o killing OpenSSH compat, I'd be happy to merge.
- @miverson seems to be having an issue with the Paramiko _server_ side implementation of these kexen, including with an OpenSSH client, which is presumably something I can try to confirm & potentially fix. Should probably become another ticket.
- In both cases, modifying one's Transport to change the preferred kex list (per @ploxiln) should be a temporary workaround.
  - I thought we had an (old!) open ticket for making this sort of thing less monkeypatchy, but I cannot find it anywhere so I may just be remembering a mental todo item.
  - I'm tempted to try and throw in a quick feature enhancement for that since I have a pending feature release today anyhow.

**Comment by ploxiln** [comment]
@edgsousa any ideas?

**Comment by edgsousa** [comment]
I reproduced the same `ssh_dispatch_run_fatal: Connection to 127.0.0.1 port 22: incorrect signature` message. It went away with this change on `paramiko/kex_group1.py` L143:
```
@@ -140,7 +140,7 @@ class KexGroup1(object):
         hm.add_mpint(self.e)
         hm.add_mpint(self.f)
         hm.add_mpint(K)
-        H = sha1(hm.asbytes()).digest()
+        H = self.hash_algo(hm.asbytes()).digest()
         self.transport._set_K_H(K, H)
         # sign it
         sig = self.transport.get_server_key().sign_ssh_data(H)
```

**Comment by ploxiln** [comment]
looks promising, thanks!

**Comment by dovahcrow** [comment]
@edgsousa Thanks! I tried the patch but it didn't fix the `Signature verification (ssh-rsa) failed` error

**Comment by edgsousa** [comment]
@dovahcrow Can you test and provide the logs with paramiko version 2.5.0 or newer? I don't think the issue you have is because of the group16-sha256 kex change. Version 2.4.1 as shown on your logs didn't have this kex officially.

Anyway, the paramiko server error reported by @miverson is fixed with this change, I think.

**Comment by dovahcrow** [comment]
@edgsousa Here's the log. Still the same issue. I guess last time I was using some git version of paramiko so the code is new but the version number is not updated.
```
DEB [20190724-10:46:45.357] thr=1   paramiko.transport: starting thread (client mode): 0x5d7bc88
DEB [20190724-10:46:45.358] thr=1   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.5.0
DEB [20190724-10:46:45.391] thr=1   paramiko.transport: Remote version/idstring: SSH-2.0-srtSSHServer_11.00
INF [20190724-10:46:45.391] thr=1   paramiko.transport: Connected (version 2.0, client srtSSHServer_11.00)
DEB [20190724-10:46:45.393] thr=1   paramiko.transport: kex algos:['diffie-hellman-group14-sha256', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group14-sha1', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group1-sha1', 'diffie-hellman-group-exchange-sha512@ssh.com', 'diffie-hellman-group16-sha256', 'diffie-hellman-group16-sha512', 'diffie-hellman-group18-sha512'] server key:['ssh-rsa'] client encrypt:['aes256-cbc', 'twofish256-cbc', 'aes128-cbc', 'blowfish-cbc', '3des-ctr', '3des-cbc'] server encrypt:['aes256-cbc', 'twofish256-cbc', 'aes128-cbc', 'blowfish-cbc', '3des-ctr', '3des-cbc'] client mac:['hmac-sha1', 'hmac-sha2-224', 'hmac-sha2-256', 'hmac-sha2-384', 'hmac-sha2-512'] server mac:['hmac-sha1', 'hmac-sha2-224', 'hmac-sha2-256', 'hmac-sha2-384', 'hmac-sha2-512'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
DEB [20190724-10:46:45.394] thr=1   paramiko.transport: Kex agreed: diffie-hellman-group16-sha512
DEB [20190724-10:46:45.394] thr=1   paramiko.transport: HostKey agreed: ssh-rsa
DEB [20190724-10:46:45.394] thr=1   paramiko.transport: Cipher agreed: aes128-cbc
DEB [20190724-10:46:45.394] thr=1   paramiko.transport: MAC agreed: hmac-sha2-256
DEB [20190724-10:46:45.394] thr=1   paramiko.transport: Compression agreed: none
INF [20190724-10:46:45.641] thr=1   paramiko.transport: Disconnect (code 3): invalid DH value
DEB [20190724-10:46:57.060] thr=1   paramiko.transport: starting thread (client mode): 0x113f2a58
DEB [20190724-10:46:57.060] thr=1   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.5.0
DEB [20190724-10:46:57.091] thr=1   paramiko.transport: Remote version/idstring: SSH-2.0-srtSSHServer_11.00
INF [20190724-10:46:57.091] thr=1   paramiko.transport: Connected (version 2.0, client srtSSHServer_11.00)
DEB [20190724-10:46:57.094] thr=1   paramiko.transport: kex algos:['diffie-hellman-group14-sha256', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group14-sha1', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group1-sha1', 'diffie-hellman-group-exchange-sha512@ssh.com', 'diffie-hellman-group16-sha256', 'diffie-hellman-group16-sha512', 'diffie-hellman-group18-sha512'] server key:['ssh-rsa'] client encrypt:['aes256-cbc', 'twofish256-cbc', 'aes128-cbc', 'blowfish-cbc', '3des-ctr', '3des-cbc'] server encrypt:['aes256-cbc', 'twofish256-cbc', 'aes128-cbc', 'blowfish-cbc', '3des-ctr', '3des-cbc'] client mac:['hmac-sha1', 'hmac-sha2-224', 'hmac-sha2-256', 'hmac-sha2-384', 'hmac-sha2-512'] server mac:['hmac-sha1', 'hmac-sha2-224', 'hmac-sha2-256', 'hmac-sha2-384', 'hmac-sha2-512'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
DEB [20190724-10:46:57.094] thr=1   paramiko.transport: Kex agreed: diffie-hellman-group16-sha512
DEB [20190724-10:46:57.094] thr=1   paramiko.transport: HostKey agreed: ssh-rsa
DEB [20190724-10:46:57.095] thr=1   paramiko.transport: Cipher agreed: aes128-cbc
DEB [20190724-10:46:57.095] thr=1   paramiko.transport: MAC agreed: hmac-sha2-256
DEB [20190724-10:46:57.095] thr=1   paramiko.transport: Compression agreed: none
INF [20190724-10:46:57.368] thr=1   paramiko.transport: Disconnect (code 3): invalid DH value
```
And 
```
DEB [20190724-10:47:06.517] thr=1   paramiko.transport: starting thread (client mode): 0x76b5cc0
DEB [20190724-10:47:06.517] thr=1   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.5.0
DEB [20190724-10:47:06.546] thr=1   paramiko.transport: Remote version/idstring: SSH-2.0-srtSSHServer_11.00
INF [20190724-10:47:06.546] thr=1   paramiko.transport: Connected (version 2.0, client srtSSHServer_11.00)
DEB [20190724-10:47:06.550] thr=1   paramiko.transport: kex algos:['diffie-hellman-group14-sha256', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group14-sha1', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group1-sha1', 'diffie-hellman-group-exchange-sha512@ssh.com', 'diffie-hellman-group16-sha256', 'diffie-hellman-group16-sha512', 'diffie-hellman-group18-sha512'] server key:['ssh-rsa'] client encrypt:['aes256-cbc', 'twofish256-cbc', 'aes128-cbc', 'blowfish-cbc', '3des-ctr', '3des-cbc'] server encrypt:['aes256-cbc', 'twofish256-cbc', 'aes128-cbc', 'blowfish-cbc', '3des-ctr', '3des-cbc'] client mac:['hmac-sha1', 'hmac-sha2-224', 'hmac-sha2-256', 'hmac-sha2-384', 'hmac-sha2-512'] server mac:['hmac-sha1', 'hmac-sha2-224', 'hmac-sha2-256', 'hmac-sha2-384', 'hmac-sha2-512'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
DEB [20190724-10:47:06.550] thr=1   paramiko.transport: Kex agreed: diffie-hellman-group16-sha512
DEB [20190724-10:47:06.550] thr=1   paramiko.transport: HostKey agreed: ssh-rsa
DEB [20190724-10:47:06.550] thr=1   paramiko.transport: Cipher agreed: aes128-cbc
DEB [20190724-10:47:06.551] thr=1   paramiko.transport: MAC agreed: hmac-sha2-256
DEB [20190724-10:47:06.551] thr=1   paramiko.transport: Compression agreed: none
ERR [20190724-10:47:06.866] thr=1   paramiko.transport: Exception: Signature verification (ssh-rsa) failed.
ERR [20190724-10:47:06.875] thr=1   paramiko.transport: Traceback (most recent call last):
ERR [20190724-10:47:06.875] thr=1   paramiko.transport:   File "/usr/local/lib/python3.7/site-packages/paramiko/transport.py", line 2016, in run
ERR [20190724-10:47:06.875] thr=1   paramiko.transport:     self.kex_engine.parse_next(ptype, m)
ERR [20190724-10:47:06.875] thr=1   paramiko.transport:   File "/usr/local/lib/python3.7/site-packages/paramiko/kex_group1.py", line 75, in parse_next
ERR [20190724-10:47:06.876] thr=1   paramiko.transport:     return self._parse_kexdh_reply(m)
ERR [20190724-10:47:06.876] thr=1   paramiko.transport:   File "/usr/local/lib/python3.7/site-packages/paramiko/kex_group1.py", line 120, in _parse_kexdh_reply
ERR [20190724-10:47:06.876] thr=1   paramiko.transport:     self.transport._verify_key(host_key, sig)
ERR [20190724-10:47:06.876] thr=1   paramiko.transport:   File "/usr/local/lib/python3.7/site-packages/paramiko/transport.py", line 1830, in _verify_key
ERR [20190724-10:47:06.876] thr=1   paramiko.transport:     self.host_key_type
ERR [20190724-10:47:06.876] thr=1   paramiko.transport: paramiko.ssh_exception.SSHException: Signature verification (ssh-rsa) failed.
ERR [20190724-10:47:06.876] thr=1   paramiko.transport:
```

**Comment by ploxiln** [comment]
edgsousa's fix was for paramiko server mode compatibility with openssh client. It was not for compatibility with other ssh implementations like srtSSHServer

**Comment by ploxiln** [comment]
(the original issue was about paramiko client connecting to a non-openssh server; there has been no fix proposed for that yet)

**Comment by edgsousa** [comment]
I guess this is an issue with Titan ssh implementation itself.
Using openssh/sftp client (and forcing the same algos as in @dovahcrow logs) I got the same error.

```
>sftp -o KexAlgorithms=diffie-hellman-group16-sha512 -o Ciphers=aes128-cbc -o HostKeyAlgorithms=ssh-rsa -o MACs=hmac-sha2-256 -v -P 2222 guest@localhost
debug1: Local version string SSH-2.0-OpenSSH_7.9
debug1: Remote protocol version 2.0, remote software version srtSSHServer_11.00
debug1: no match: srtSSHServer_11.00
debug1: Authenticating to localhost:2222 as 'guest'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: diffie-hellman-group16-sha512
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: aes128-cbc MAC: hmac-sha2-256 compression: none
debug1: kex: client->server cipher: aes128-cbc MAC: hmac-sha2-256 compression: none
debug1: kex: diffie-hellman-group16-sha512 need=32 dh_need=32
debug1: kex: diffie-hellman-group16-sha512 need=32 dh_need=32
debug1: sending SSH2_MSG_KEXDH_INIT
debug1: expecting SSH2_MSG_KEXDH_REPLY
Received disconnect from ::1 port 2222:3: invalid DH value
Disconnected from ::1 port 2222
```

Titan logs say
```
2019-07-25 11:50:57 [2/1832/1b44] SFTP-Engine: We terminated the session with the following reason: SSH_DISCONNECT_KEY_EXCHANGE_FAILED, description: invalid DH value
```

If I use group14-sha256 instead it works. 

You should raise this issue with South River, the company behind Titan FTP software.

**Comment by dovahcrow** [comment]
@edgsousa Thanks for the diagnostic! I can confirm this behavior on my side. Feel free to close this issue.

**Comment by keshav0129** [comment]
@edgsousa Which verison of paramiko has the fix for "paramiko.ssh_exception.SSHException: Signature verification (ssh-rsa) failed."?

**Comment by PabloRuizCuevas** [comment]
Hi, I could connect to the host: srtSSHServer_11.00  aka filezilla.

this was the journey. Trying to connect with paramiko gave:

`
SSHException: Signature verification (ssh-rsa) failed.`

I tried in OpenSSH_8.9p1 and i got
`
Unable to negotiate with 20.xxx.xx.122 port 22: no matching host key type found. Their offer: ssh-rsa`

So i tried: 
sftp -i pem_file.pem -o HostKeyAlgorithms=+rsa-sha2-512 -o PubkeyAcceptedKeyTypes=rsa-sha2-512 imogate@20.199.74.122

And it works!

But what about paramiko? still didn't work,  so after some research: i did:

```
    paramiko.transport.Transport._preferred_kex = (
        'ecdh-sha2-nistp256',
        'ecdh-sha2-nistp384',
        'ecdh-sha2-nistp521',
        # 'diffie-hellman-group16-sha512',  # disable
        'diffie-hellman-group14-sha1',
        'diffie-hellman-group1-sha1',
    )
    paramiko.transport.Transport._preferred_pubkeys = (
        "ssh-ed25519",
        "ecdsa-sha2-nistp256",
        "ecdsa-sha2-nistp384",
        "ecdsa-sha2-nistp521",
        "ssh-rsa", # this is moved 2 positions up
        "rsa-sha2-512",
        "rsa-sha2-256",
        "ssh-dss",
    )
    paramiko.transport.Transport._preferred_pubkeys = (
        "ssh-ed25519",
        "ecdsa-sha2-nistp256",
        "ecdsa-sha2-nistp384",
        "ecdsa-sha2-nistp521",
        "ssh-rsa",  # this is moved 2 positions up
        "rsa-sha2-512",
        "rsa-sha2-256",
        "ssh-dss",
    )
```

I can't tell much on why, it seems there is a bug between openSSH/paramiko and srtSSHServer_11 when using rsa-sha2-xxx. 
I could not figure out exactly how, and using ssh-rsa is not an optimal solution, but at least is something.

**Comment by jun66j5** [comment]
@PabloRuizCuevas You shouldn't comment on the old and unrelated issue. Instead, create new issue with support tag.

**Comment by PabloRuizCuevas** [comment]
@jun66j5 I'm quite sure the issue is the same. but i can create a new issue
