### ISSUE TITLE
FIPS - cannot use MD5

### ISSUE THREAD

**Issue by cingeyedog** [paramiko/paramiko#396]
can the pkey.py be updated so that it doesnt use MD5?  

MD5 cannot be used in conjunction with FIPS.  

Directions for turning on FIPS in RHEL6: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Security_Guide/sect-Security_Guide-Federal_Standards_And_Regulations-Federal_Information_Processing_Standard.html

**Comment by yaccz** [comment]
ssh -vvv <host-working-with-paramiko>
debug1: kex: server->client aes128-ctr hmac-md5-etm@openssh.com none

ssh -vvv <fips-enabled-host-not-working-with-paramiko>
debug1: kex: server->client aes128-ctr hmac-sha1 none

So I guess, exactly what the OP says

**Comment by Ismael** [comment]
This pull request fixes this: https://github.com/paramiko/paramiko/pull/1103
To install run:

>  pip install -e git+https://github.com/ioparaskev/paramiko#egg=paramiko

**Comment by dsethi** [comment]
Has this issue been solved? We are running into same issue where we have to use paramiko on a fips enabled kernel. In case not, are there alternate python ssh libraries for this?

**Comment by thukk** [comment]
> This pull request fixes this: #1103
> To install run:
> 
> > pip install -e git+https://github.com/ioparaskev/paramiko#egg=paramiko

this does indeed allow Paramiko to work on FIPS enabled machines.  There is a CryptographyDeprecationWarning for ecdsakey.py and kex_ecdh_nist.py.  It recommends using EllipticCurvePublicKey instead of EllipticCurvePublicNumbers.

**Comment by dsethi** [comment]
Thanks for that Thukk. Since the PR is not merged/failed some tests initially, did it lead to any issues? How long have you run this change?

**Comment by thukk** [comment]
> Thanks for that Thukk. Since the PR is not merged/failed some tests initially, did it lead to any issues? How long have you run this change?

Thus far, no.  Set it up today.  I am using Paramiko as a part of Fabric.  My Fabric scripts are now working (aside from the warning I mentioned before).

**Comment by avidspartan1** [comment]
We've found the paramiko transport to work well for us, except when it comes to FIPS. Would love to see this PR accepted.

**Comment by subodh2691** [comment]
I am facing similar issue and cloning of repo outside org is blocked in my machine. When this change will be going in to latest version of paramiko?

**Comment by naman0805** [comment]
Any updates on whether this change ( https://github.com/paramiko/paramiko/pull/1103 ) is going to get merged in the master branch?
If Yes, do we have any tentative timelines?

**Comment by neutronscott** [comment]
While waiting on that PR I guess I can do this to use paramiko if anyone else needs it:

`pkey.py:        return md5(self.asbytes()).digest()`

change to

`pkey.py:        return md5(self.asbytes(), usedforsecurity=False).digest()`

**Comment by zthomas2** [comment]
Bumping this issue, as it is still not fixed as of paramiko 2.11.0. This issue has been open for 8 years, can I expect that it will never be addressed? If so, could it be stated as such so that I can put effort into finding an alternate solution to paramiko for my use case?

**Comment by gubenkoved** [comment]
Any updates on this one? 🥲

**Comment by bskinn** [comment]
Flagging this to include/consider in the key/auth rewrite of #387.

**Comment by jewest27** [comment]
After a few hours of troubleshooting, I learned I had this problem too.  To make matters worse, it seemed to fail with ValueError: unknown reasons.  Super helpful!

I wanted to drop my solution here, since I hadn't found another solution after a while of searching.  I took the monkey patch approach and was able to get past my use case.  Hope it helps someone!

`PKey.get_fingerprint = lambda x: sha256(x.asbytes()).digest() #monkeypatch for FIPS`

**Comment by bskinn** [comment]
bitprophet has been working on improving the flexibility of the key/auth tooling lately, per #387 and #23. Please check out the **experimental** new features described in the [3.2.0 paramiko CHANGELOG] (including the new `OpenSSHAuthStrategy` implementation in [Fabric 3.1.0]) -- it's possible that they may enable what is needed here on the user side, and not require changes to `paramiko` itself.

I'm not deeply familiar with what the current features enable, so I can't say for sure whether they address this use case. We would greatly appreciate any investigation anyone might be able to do and report back here, though. The new features will be fully added and finalized over the next few minor versions, so now is a great time to make sure specific needs are factored into the functionality.

[3.2.0 paramiko changelog]: https://www.paramiko.org/changelog.html#3.2.0
[fabric 3.1.0]: https://www.fabfile.org/changelog.html#3.1.0

**Comment by jun66j5** [comment]
> I wanted to drop my solution here, since I hadn't found another solution after a while of searching. I took the monkey patch approach and was able to get past my use case. Hope it helps someone!
> 
> `PKey.get_fingerprint = lambda x: sha256(x.asbytes()).digest() #monkeypatch for FIPS`

`PKey.fingerprint` property has been added in paramiko 3.2.0. Stop monkey-patching and use the `.fingerprint` property instead of `.get_fingerprint()` method.

```pycon
>>> import paramiko
>>> key = paramiko.RSAKey.generate(bits=4096)
>>> key.fingerprint
'SHA256:61p1dnTZCEcYbfyN1iHujMpUw/xfPSZh++DkyWpTRVE'
>>>
```

**Comment by bskinn** [comment]
For my reference: is the solution to the original issue **just** implementation of a fingerprinting method that FIPS will accept?

If so, does that mean that the current SHA256 algorithm used for the `.fingerprint` property should make FIPS work correctly -- and, thus, this issue is resolved?

**Comment by gubenkoved** [comment]
Looks like paramiko 3.3.1 uses `get_fingerprint` internally that still uses MD5 and it still fails under FIPS-compliant OpenSSL.

```
>>> import paramiko
>>> key = paramiko.RSAKey.generate(bits=4096)
>>> key.fingerprint
'SHA256:ZPEwJRZVeQdS/PaYDmHtMPZbmL0ac2+uUdren352jTY'
>>> key.get_fingerprint()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/paramiko/pkey.py", line 344, in get_fingerprint
    return md5(self.asbytes()).digest()
ValueError: [digital envelope routines] unsupported
```

```
   ...
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 460, in connect
    self._policy.missing_host_key(
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 859, in missing_host_key
    key.get_name(), hostname, hexlify(key.get_fingerprint())
  File "/usr/local/lib/python3.10/dist-packages/paramiko/pkey.py", line 344, in get_fingerprint
    return md5(self.asbytes()).digest()
ValueError: [digital envelope routines] unsupported
```

**Comment by bskinn** [comment]
Searching the codebase for `get_fingerprint(`, I see six points of use outside of demos and tests, all in `client.py`, and all for debug logging purposes (all links going to the current `main` head commit of d5117fc):

- The three subclasses of `MissingHostKeyPolicy`:
  - [`AutoAddPolicy`](https://github.com/paramiko/paramiko/blob/d5117fc7988e3ede445ca09d7ffc95d4263445c3/paramiko/client.py#L859)
  - [`RejectPolicy`](https://github.com/paramiko/paramiko/blob/d5117fc7988e3ede445ca09d7ffc95d4263445c3/paramiko/client.py#L874)
  - [`WarningPolicy`](https://github.com/paramiko/paramiko/blob/d5117fc7988e3ede445ca09d7ffc95d4263445c3/paramiko/client.py#L891)
- [Agent-based key discovery](https://github.com/paramiko/paramiko/blob/d5117fc7988e3ede445ca09d7ffc95d4263445c3/paramiko/client.py#L749)
- [Explicit key is passed](https://github.com/paramiko/paramiko/blob/d5117fc7988e3ede445ca09d7ffc95d4263445c3/paramiko/client.py#L712)
- [In `_key_from_filepath()`](https://github.com/paramiko/paramiko/blob/d5117fc7988e3ede445ca09d7ffc95d4263445c3/paramiko/client.py#L643)

Seems like it should be unproblematic to upgrade the fingerprint algorithm used in this logging to SHA256. Created #2287 for this.

**Comment by bkyarnell** [comment]
Lot of comments, but still not clear if paramiko is resolved for FIPS compatibility?

This was suggested:
paramiko.PKey.get_fingerprint = lambda x: sha256(x.asbytes()).digest() #monkeypatch for FIPS

However, returns an error:
NameError: name 'sha256' is not defined

Any suggestions?

**Comment by storyG** [comment]
> Lot of comments, but still not clear if paramiko is resolved for FIPS compatibility?
> 
> This was suggested: `paramiko.PKey.get_fingerprint = lambda x: sha256(x.asbytes()).digest() #monkeypatch for FIPS`
> 
> However, returns an error: `NameError: name 'sha256' is not defined`
> 
> Any suggestions?

Solved this issue by importing import hashlib.

import hashlib
paramiko.PKey.get_fingerprint = lambda x: hashlib.sha256(x.asbytes()).digest() # monkeypatch for FIPS

**Comment by bkyarnell** [comment]
@storyG 
Thanks for that!  

I'm using  netmiko for network management and netmiko has paramiko as a dependency.  Adding this to the top of my code after my imports allows SHA-256 vs. MD5 to be used for use with the ssh transport.

```
#Patch to allow paramiko to use SHA-256 vs MD5
import paramiko
from hashlib import sha256
paramiko.PKey.get_fingerprint = lambda x: sha256(x.asbytes()).digest()
```

Hopefully, this can be fixed in a future iteration of paramiko to allow the encryption hash to be selected.

**Comment by see-quick** [comment]
Hello, guys any reason to not adopt a solution using `SHA-256` instead of `MD5`? 

^^ @bitprophet
