### ISSUE TITLE
Support dual AuthenticationMethods

### ISSUE THREAD

**Issue by majuscule** [paramiko/paramiko#841]
OpenSSH 6.2 introduced multiple AuthenticationMethods ([changelog](https://lwn.net/Articles/543961/)). Paramiko improperly fails to authenticate on a server with this feature enabled, despite being supplied the correct parameters.

```
DEBUG:paramiko.transport:Attempting public-key auth...
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Auth banner: 
INFO:paramiko.transport:Authentication continues...
DEBUG:paramiko.transport:Methods: [u'password', u'keyboard-interactive']
DEBUG:paramiko.transport:[chan 0] Max packet in: 32468 bytes
INFO:paramiko.transport:Disconnect (code 2): received packet inappropriate for current authentication state
```

Contrast with `ssh` binary:

```
debug1: Next authentication method: publickey
debug1: Offering RSA public key: .ssh/id_rsa
debug1: Server accepts key: pkalg ssh-rsa blen 279
debug1: key_parse_private2: missing begin marker
debug1: read PEM private key done: type RSA
Authenticated with partial success.
debug1: Authentications that can continue: password,keyboard-interactive
debug1: Next authentication method: keyboard-interactive
Enter password: 
debug1: Authentication succeeded (keyboard-interactive).
```

**Comment by majuscule** [comment]
Support was supposedly implemented in https://github.com/paramiko/paramiko/commit/83a932a1b39a0e81ffe1e5c885151d2db7ddcf4e, but I can't seem to get it to work there for a bisect either.

**Comment by adplax18** [comment]
I am having this issue as well.  Is there a plan to make this fix or should I be searching for other solutions?

**Comment by bitprophet** [comment]
I'd say this falls under #387 - tl;dr the auth code knows about multiple auth methods but the implementation is quite slipshod and only works for a couple well-tested paths (such as private key + TOTP).

Further, those well-tested paths were only fixed in semi recent times, so if you're on anything older than 1.16 even those won't work (see http://www.paramiko.org/changelog.html#1.16.0 where it mentions #467).

**Comment by vikash32** [comment]
i am using paramiko 2.4.1, but still getting same. Is there specific way to achieve this.
`>>> paramiko.__version__`
`'2.4.1'`

`DEB [20180703-19:53:25.737] thr=2   paramiko.transport: Attempting public-key auth...`
`DEB [20180703-19:53:25.767] thr=1   paramiko.transport: userauth is OK`
`INF [20180703-19:53:25.770] thr=1   paramiko.transport: Auth banner: EFT Server Enterprise 7.3.3.21`
`INF [20180703-19:53:25.775] thr=1   paramiko.transport: Authentication continues...`
`DEB [20180703-19:53:25.775] thr=1   paramiko.transport: Methods: [u'password', u'keyboard-interactive']`
`DEB [20180703-19:53:25.803] thr=2   paramiko.transport: [chan 0] Max packet in: 32768 bytes`
`INF [20180703-19:53:25.806] thr=1   paramiko.transport: Disconnect (code 2): received packet inappropriate for current authentication state`
